// Templates and Prompt Library — shared list/detail patterns for authored artifacts.
// Both load from manifests in data/templates.json + data/prompts.json (generated by index_artifacts.py).

function renderMarkdown(md) {
  if (!md) return '';
  if (window.marked && window.DOMPurify) {
    try {
      return window.DOMPurify.sanitize(window.marked.parse(md));
    } catch (e) {
      console.error('markdown render error', e);
    }
  }
  // Fallback: escape and render as <pre>
  const esc = String(md).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return '<pre style="white-space:pre-wrap;font-family:JetBrains Mono,monospace;font-size:13px">' + esc + '</pre>';
}

function copyToClipboard(text) {
  if (navigator.clipboard && navigator.clipboard.writeText) {
    return navigator.clipboard.writeText(text);
  }
  // Fallback for older browsers
  const ta = document.createElement('textarea');
  ta.value = text;
  ta.style.position = 'fixed';
  ta.style.opacity = '0';
  document.body.appendChild(ta);
  ta.select();
  try { document.execCommand('copy'); } catch (e) {}
  document.body.removeChild(ta);
  return Promise.resolve();
}

function downloadAsFile(text, filename, mime) {
  const blob = new Blob([text], { type: mime || 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function CopyBtn({ text, label, filename }) {
  const [copied, setCopied] = React.useState(false);
  const onCopy = async () => {
    await copyToClipboard(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  };
  return (
    <div style={{display:'flex', gap:8, flexWrap:'wrap'}}>
      <button className="btn btn-primary" onClick={onCopy}>
        {copied ? window.SIcon.check : window.SIcon.copy} {copied ? 'Copied!' : (label || 'Copy')}
      </button>
      {filename && (
        <button className="btn btn-ghost" onClick={() => downloadAsFile(text, filename, 'text/markdown')}>
          {window.SIcon.download} Download
        </button>
      )}
    </div>
  );
}

function ArtifactCard({ item, kind, onOpen }) {
  const typeLabel = kind === 'template' ? 'Template' : 'Prompt Pack';
  const promptCount = (item.prompts || []).length;
  return (
    <article className="res-card" onClick={() => onOpen(item)}>
      <div className="res-head">
        <span className="type-pill">{typeLabel}</span>
      </div>
      <div className="res-title">{item.title}</div>
      <div className="res-blurb">{item.summary}</div>
      <div className="res-foot">
        <div className="res-tags">
          {item.estimated_time && <span className="tag tag-meta">{item.estimated_time}</span>}
          {kind === 'prompt' && <span className="tag tag-meta">{promptCount} prompts</span>}
        </div>
        <span className="level-badge" data-level={item.difficulty}>{item.difficulty}</span>
      </div>
    </article>
  );
}

function MetaBlock({ label, items }) {
  if (!items || items.length === 0) return null;
  return (
    <div style={{marginTop:14}}>
      <div className="art-mlabel">{label}</div>
      <ul className="art-mlist">
        {items.map((u, i) => <li key={i}>{u}</li>)}
      </ul>
    </div>
  );
}

function ArtifactDetail({ item, kind, onClose }) {
  React.useEffect(() => {
    const onKey = (e) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  const open = !!item;

  if (!open) {
    return (
      <>
        <div className="panel-overlay" data-open={false}></div>
        <aside className="panel" data-open={false}></aside>
      </>
    );
  }

  const isTemplate = kind === 'template';
  const body = isTemplate ? (item.template_body_markdown || '') : '';
  const renderedBody = isTemplate ? renderMarkdown(body) : '';

  return (
    <>
      <div className="panel-overlay" data-open={open} onClick={onClose}></div>
      <aside className="panel art-panel" data-open={open}>
        <div className="panel-head">
          <span className="type-pill">{isTemplate ? 'Template' : 'Prompt Pack'}</span>
          <button className="icon-btn" onClick={onClose}>{window.SIcon.close}</button>
        </div>
        <div className="panel-body">
          <h2>{item.title}</h2>
          <p className="art-summary">{item.summary}</p>

          {item.why_it_matters && (
            <div style={{marginTop:14}}>
              <div className="art-mlabel">Why it matters</div>
              <p className="art-para">{item.why_it_matters}</p>
            </div>
          )}

          <MetaBlock label="When to use" items={item.when_to_use} />
          <MetaBlock label="Not for" items={item.not_for} />

          <div className="panel-meta">
            <div className="cell"><div className="k">Practice</div><div className="v">{item.practice_label}</div></div>
            <div className="cell"><div className="k">Difficulty</div><div className="v">{item.difficulty}</div></div>
            {item.estimated_time && <div className="cell"><div className="k">Est. time</div><div className="v">{item.estimated_time}</div></div>}
            <div className="cell"><div className="k">Audience</div><div className="v">{(item.audience||[]).join(' · ')}</div></div>
            {item.version && <div className="cell"><div className="k">Version</div><div className="v">{item.version}</div></div>}
            {item.updated_at && <div className="cell"><div className="k">Updated</div><div className="v">{item.updated_at}</div></div>}
          </div>

          {isTemplate && body && (
            <>
              <div style={{marginTop:18}}>
                <CopyBtn text={body} label="Copy template" filename={`${item.slug || 'template'}.md`} />
              </div>
              <div className="art-divider"></div>
              <div className="art-md-label">Template body</div>
              <div className="md-body" dangerouslySetInnerHTML={{__html: renderedBody}}></div>
            </>
          )}

          {!isTemplate && (item.prompts || []).length > 0 && (
            <>
              <div className="art-divider"></div>
              <div className="art-md-label">Prompts in this pack</div>
              {item.prompts.map((p, i) => (
                <div key={p.id || i} className="prompt-block">
                  <div className="prompt-head">
                    <span className="prompt-num">#{i + 1}</span>
                    <span className="prompt-name">{p.name || p.use_case}</span>
                  </div>
                  {p.use_case && p.use_case !== p.name && (
                    <div className="prompt-usecase">{p.use_case}</div>
                  )}
                  <pre className="prompt-text">{p.prompt}</pre>
                  <div style={{marginTop:8, marginBottom:4}}>
                    <CopyBtn text={p.prompt} label="Copy prompt" />
                  </div>
                  {(p.inputs || p.output_format || p.review_checklist) && (
                    <details className="prompt-details">
                      <summary>Inputs · Output format · Review checklist</summary>
                      {p.inputs && p.inputs.length > 0 && (
                        <div style={{marginTop:8}}>
                          <div className="art-mlabel">Inputs</div>
                          <ul className="art-mlist">{p.inputs.map((x, j) => <li key={j}>{x}</li>)}</ul>
                        </div>
                      )}
                      {p.output_format && p.output_format.length > 0 && (
                        <div style={{marginTop:8}}>
                          <div className="art-mlabel">Output format</div>
                          <ul className="art-mlist">{p.output_format.map((x, j) => <li key={j}>{x}</li>)}</ul>
                        </div>
                      )}
                      {p.review_checklist && p.review_checklist.length > 0 && (
                        <div style={{marginTop:8}}>
                          <div className="art-mlabel">Review checklist</div>
                          <ul className="art-mlist">{p.review_checklist.map((x, j) => <li key={j}>{x}</li>)}</ul>
                        </div>
                      )}
                    </details>
                  )}
                </div>
              ))}
            </>
          )}
        </div>
      </aside>
    </>
  );
}

function ArtifactsView({ kind }) {
  const data = kind === 'template' ? window.ARCH_TEMPLATES : window.ARCH_PROMPTS;
  const items = (kind === 'template' ? data?.templates : data?.prompts) || [];
  const labels = data?.practice_labels || {};
  const [selected, setSelected] = React.useState(null);
  const [practiceFilter, setPracticeFilter] = React.useState(null);

  const filtered = practiceFilter ? items.filter(t => t.practice_folder === practiceFilter) : items;

  // Group by practice for display
  const groups = {};
  for (const t of filtered) {
    const k = t.practice_folder || 'other';
    if (!groups[k]) groups[k] = [];
    groups[k].push(t);
  }

  const heroTitle = kind === 'template' ? 'Templates' : 'Prompt Library';
  const heroBlurb = kind === 'template'
    ? `${items.length} ready-to-use templates for engineering managers, directors, VPs, and CTOs. Copy or download as Markdown.`
    : `${items.length} prompt packs for engineering leadership workflows. Each pack contains multiple prompts ready for ChatGPT, Claude, or Gemini.`;

  return (
    <>
      <div className="rm-hero">
        <h2>{heroTitle}</h2>
        <p>{heroBlurb}</p>
        <div className="path-pills" style={{marginTop:14}}>
          <button className="pill" data-active={!practiceFilter} onClick={() => setPracticeFilter(null)}>All</button>
          {Object.keys(labels).map(k => (
            <button
              key={k}
              className="pill"
              data-active={practiceFilter === k}
              onClick={() => setPracticeFilter(p => p === k ? null : k)}
            >
              {labels[k]}
            </button>
          ))}
        </div>
      </div>

      <div className="rm-body">
        {Object.keys(groups).length === 0 ? (
          <div className="empty">
            <div className="mono-line">// EMPTY</div>
            <p>No items match the current filter.</p>
          </div>
        ) : (
          Object.entries(groups).map(([practice, gItems]) => (
            <div key={practice} className="art-group">
              <h3 className="art-group-head">{labels[practice] || practice} <span className="art-group-count">{gItems.length}</span></h3>
              <div className="res-grid">
                {gItems.map(t => (
                  <ArtifactCard key={t.id} item={t} kind={kind} onOpen={setSelected} />
                ))}
              </div>
            </div>
          ))
        )}
      </div>

      <ArtifactDetail item={selected} kind={kind} onClose={() => setSelected(null)} />
    </>
  );
}

window.TemplatesView = () => <ArtifactsView kind="template" />;
window.PromptsView = () => <ArtifactsView kind="prompt" />;
